// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Login(ctx context.Context, id uuid.UUID) (Auth, error)
	Register(ctx context.Context, arg RegisterParams) (Auth, error)
}

var _ Querier = (*Queries)(nil)
